/**
 * @file learning.types.ts
 * @description Type definitions for learning from corrections system
 * 
 * Part of Phase 2.3: Learning from Corrections
 * Tracks human edits to AI-generated code and uses them as training data
 */

/**
 * Correction type
 */
export type CorrectionType = 
  | 'syntax-fix'      // Fixed syntax error
  | 'import-fix'      // Fixed import statement
  | 'type-fix'        // Fixed type annotation
  | 'logic-fix'       // Fixed logic error
  | 'style-fix'       // Fixed code style
  | 'refactor'        // Refactored code structure
  | 'optimization'    // Performance optimization
  | 'security-fix'    // Security vulnerability fix
  | 'other';          // Other correction

/**
 * Correction metadata
 */
export interface Correction {
  /** Unique correction ID */
  id: string;
  /** Snapshot ID that was corrected */
  snapshotId: string;
  /** Task description */
  task: string;
  /** Execution mode */
  mode: string;
  /** File that was corrected */
  filePath: string;
  /** Original AI-generated content */
  originalContent: string;
  /** User's corrected content */
  correctedContent: string;
  /** Diff between original and corrected */
  diff: string;
  /** Type of correction */
  correctionType: CorrectionType;
  /** Timestamp when correction was detected */
  timestamp: number;
  /** Project root directory */
  projectRoot: string;
  /** Programming language */
  language?: string;
  /** Confidence score for correction type detection (0-1) */
  confidence: number;
}

/**
 * Correction detection config
 */
export interface CorrectionDetectionConfig {
  /** Project root directory */
  projectRoot: string;
  /** Snapshot ID to check for corrections */
  snapshotId: string;
  /** Files that were generated by AI */
  generatedFiles: string[];
  /** Time window to check for corrections (default: 1 hour) */
  timeWindow?: number;
}

/**
 * Correction detection result
 */
export interface CorrectionDetectionResult {
  /** Detection was successful */
  success: boolean;
  /** Detected corrections */
  corrections: Correction[];
  /** Error message if detection failed */
  error?: string;
  /** Duration in milliseconds */
  duration: number;
}

/**
 * Learning example for LLM prompts
 */
export interface LearningExample {
  /** Task description */
  task: string;
  /** What the AI generated incorrectly */
  incorrect: string;
  /** What the user corrected it to */
  correct: string;
  /** Correction type */
  correctionType: CorrectionType;
  /** How many times this pattern has occurred */
  occurrences: number;
  /** Average confidence score */
  confidence: number;
}

/**
 * Learning statistics
 */
export interface LearningStats {
  /** Total corrections tracked */
  totalCorrections: number;
  /** Corrections by type */
  correctionsByType: Record<CorrectionType, number>;
  /** Most common correction type */
  mostCommonType: CorrectionType | null;
  /** Accuracy improvement over time (0-1) */
  accuracyImprovement: number;
  /** Average corrections per execution */
  avgCorrectionsPerExecution: number;
  /** Files most frequently corrected */
  topCorrectedFiles: Array<{ filePath: string; correctionCount: number }>;
}

/**
 * Learning database interface
 */
export interface ILearningDatabase {
  /** Save correction to database */
  saveCorrection(correction: Correction): Promise<void>;
  
  /** Get correction by ID */
  getCorrection(correctionId: string): Promise<Correction | undefined>;
  
  /** Get all corrections for a project */
  getCorrections(projectRoot: string): Promise<Correction[]>;
  
  /** Get corrections for a specific snapshot */
  getSnapshotCorrections(snapshotId: string): Promise<Correction[]>;
  
  /** Get corrections by type */
  getCorrectionsByType(projectRoot: string, type: CorrectionType): Promise<Correction[]>;
  
  /** Get corrections for a specific file */
  getFileCorrections(projectRoot: string, filePath: string): Promise<Correction[]>;
  
  /** Get learning examples for LLM prompts */
  getLearningExamples(projectRoot: string, limit?: number): Promise<LearningExample[]>;
  
  /** Get learning statistics */
  getStats(projectRoot: string): Promise<LearningStats>;
  
  /** Delete correction */
  deleteCorrection(correctionId: string): Promise<void>;
  
  /** Delete all corrections for a project */
  deleteProjectCorrections(projectRoot: string): Promise<number>;
}

/**
 * Correction learning config
 */
export interface CorrectionLearningConfig {
  /** Enable learning from corrections (default: true) */
  enabled?: boolean;
  /** Maximum learning examples to include in prompts (default: 5) */
  maxExamples?: number;
  /** Minimum confidence score to include example (default: 0.7) */
  minConfidence?: number;
  /** Include correction type in prompt (default: true) */
  includeCorrectionType?: boolean;
  /** Time window to check for corrections after execution (default: 1 hour) */
  correctionDetectionWindow?: number;
}

/**
 * Correction learning result
 */
export interface CorrectionLearningResult {
  /** Learning was successful */
  success: boolean;
  /** Number of corrections detected */
  correctionsDetected: number;
  /** Number of learning examples generated */
  examplesGenerated: number;
  /** Error message if learning failed */
  error?: string;
  /** Duration in milliseconds */
  duration: number;
}
