export function buildPrCommentBody(options: {
  dagName: string;
  runId: string;
  status: 'success' | 'partial' | 'failed';
  lanes: Array<{ id: string; status: string; durationMs: number }>;
  totalCostUSD: number;
  summary?: string;
}): string {
  const { dagName, runId, status, lanes, totalCostUSD, summary } = options;

  const statusEmoji = status === 'success' ? '✅' : status === 'partial' ? '⚠️' : '❌';
  const marker = `<!-- ai-kit:pr-comment -->`;

  const laneRows = lanes
    .map((l) => `| ${l.id} | ${l.status} | ${(l.durationMs / 1000).toFixed(1)}s |`)
    .join('\n');

  return [
    marker,
    `## ${statusEmoji} AI Review — ${dagName}`,
    '',
    `**Run ID:** \`${runId}\`  **Status:** ${status}  **Cost:** $${totalCostUSD.toFixed(4)}`,
    '',
    summary ? `### Summary\n${summary}\n` : '',
    '### Lane Results',
    '',
    '| Lane | Status | Duration |',
    '|------|--------|----------|',
    laneRows,
    '',
    `<sub>Generated by [ai-agencee](https://github.com/binaryjack/ai-agencee) — ${new Date().toISOString()}</sub>`,
  ]
    .filter((l) => l !== null)
    .join('\n');
}
